---
efiSystemPartition: /boot
userSwapChoices: [ none ]
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType: ext4
availableFileSystemTypes: [ ext4 ]
