---
modules-search: [ local, /usr/lib/calamares/modules ]
branding: janusos
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
sequence:
  - show: [ welcome, partition, summary ]
  - exec: [ janusinstall ]
  - show: [ finished ]
